sdm660: mm: Removed mm_trace_rss_stat as its no longer needed by memory management drivers
mm/built-in.o: In function `add_mm_counter_fast':
usercopy.c:(.text+0x22300): undefined reference to `mm_trace_rss_stat'
mm/built-in.o: In function `sync_mm_rss':
usercopy.c:(.text+0x22a44): undefined reference to `mm_trace_rss_stat'
mm/built-in.o: In function `unmap_single_vma':
usercopy.c:(.text+0x23864): undefined reference to `mm_trace_rss_stat'
mm/built-in.o: In function `copy_page_range':
usercopy.c:(.text+0x24c7c): undefined reference to `mm_trace_rss_stat'
mm/built-in.o: In function `try_to_unmap_one':
usercopy.c:(.text+0x2d250): undefined reference to `mm_trace_rss_stat'
mm/built-in.o:usercopy.c:(.text+0x2d284): more undefined references to `mm_trace_rss_stat' follow

Signed-off-by: mprabhat774 <mprabhat774@gmail.com>